import type { TelegramBotApiInputFile, TelegramBotApiType } from './telegram-bot-api-types';

/** Generated from Telegram Bot API 10.3 parameter tables (2026-08-29). */
export const TELEGRAM_METHOD_PARAMETER_SPEC = {
  getUpdates: { required: [], optional: ['offset', 'limit', 'timeout', 'allowed_updates'], types: { 'offset': 'Integer', 'limit': 'Integer', 'timeout': 'Integer', 'allowed_updates': 'Array of String' } },
  setWebhook: { required: ['url'], optional: ['certificate', 'ip_address', 'max_connections', 'allowed_updates', 'drop_pending_updates', 'secret_token'], types: { 'url': 'String', 'certificate': 'InputFile', 'ip_address': 'String', 'max_connections': 'Integer', 'allowed_updates': 'Array of String', 'drop_pending_updates': 'Boolean', 'secret_token': 'String' } },
  deleteWebhook: { required: [], optional: ['drop_pending_updates'], types: { 'drop_pending_updates': 'Boolean' } },
  getWebhookInfo: { required: [], optional: [], types: {  } },
  getMe: { required: [], optional: [], types: {  } },
  logOut: { required: [], optional: [], types: {  } },
  close: { required: [], optional: [], types: {  } },
  sendMessage: { required: ['chat_id', 'text'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'parse_mode', 'entities', 'link_preview_options', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'text': 'String', 'parse_mode': 'String', 'entities': 'Array of MessageEntity', 'link_preview_options': 'LinkPreviewOptions', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  forwardMessage: { required: ['chat_id', 'from_chat_id', 'message_id'], optional: ['message_thread_id', 'direct_messages_topic_id', 'video_start_timestamp', 'disable_notification', 'protect_content', 'message_effect_id', 'suggested_post_parameters'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'from_chat_id': 'Integer or String', 'video_start_timestamp': 'Integer', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'message_id': 'Integer' } },
  forwardMessages: { required: ['chat_id', 'from_chat_id', 'message_ids'], optional: ['message_thread_id', 'direct_messages_topic_id', 'disable_notification', 'protect_content'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'from_chat_id': 'Integer or String', 'message_ids': 'Array of Integer', 'disable_notification': 'Boolean', 'protect_content': 'Boolean' } },
  copyMessage: { required: ['chat_id', 'from_chat_id', 'message_id'], optional: ['message_thread_id', 'direct_messages_topic_id', 'video_start_timestamp', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'from_chat_id': 'Integer or String', 'message_id': 'Integer', 'video_start_timestamp': 'Integer', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  copyMessages: { required: ['chat_id', 'from_chat_id', 'message_ids'], optional: ['message_thread_id', 'direct_messages_topic_id', 'disable_notification', 'protect_content', 'remove_caption'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'from_chat_id': 'Integer or String', 'message_ids': 'Array of Integer', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'remove_caption': 'Boolean' } },
  sendPhoto: { required: ['chat_id', 'photo'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'has_spoiler', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'photo': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'has_spoiler': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendLivePhoto: { required: ['chat_id', 'live_photo', 'photo'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'has_spoiler', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'live_photo': 'InputFile or String', 'photo': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'has_spoiler': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendAudio: { required: ['chat_id', 'audio'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'caption', 'parse_mode', 'caption_entities', 'duration', 'performer', 'title', 'thumbnail', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'audio': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'duration': 'Integer', 'performer': 'String', 'title': 'String', 'thumbnail': 'InputFile or String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendDocument: { required: ['chat_id', 'document'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'thumbnail', 'caption', 'parse_mode', 'caption_entities', 'disable_content_type_detection', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'document': 'InputFile or String', 'thumbnail': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'disable_content_type_detection': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendVideo: { required: ['chat_id', 'video'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'duration', 'width', 'height', 'thumbnail', 'cover', 'start_timestamp', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'has_spoiler', 'supports_streaming', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'video': 'InputFile or String', 'duration': 'Integer', 'width': 'Integer', 'height': 'Integer', 'thumbnail': 'InputFile or String', 'cover': 'InputFile or String', 'start_timestamp': 'Integer', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'has_spoiler': 'Boolean', 'supports_streaming': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendAnimation: { required: ['chat_id', 'animation'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'duration', 'width', 'height', 'thumbnail', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'has_spoiler', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'animation': 'InputFile or String', 'duration': 'Integer', 'width': 'Integer', 'height': 'Integer', 'thumbnail': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'has_spoiler': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendVoice: { required: ['chat_id', 'voice'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'caption', 'parse_mode', 'caption_entities', 'duration', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'voice': 'InputFile or String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'duration': 'Integer', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendVideoNote: { required: ['chat_id', 'video_note'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'duration', 'length', 'thumbnail', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'video_note': 'InputFile or String', 'duration': 'Integer', 'length': 'Integer', 'thumbnail': 'InputFile or String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendPaidMedia: { required: ['chat_id', 'star_count', 'media'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'payload', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'star_count': 'Integer', 'media': 'Array of InputPaidMedia', 'payload': 'String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendMediaGroup: { required: ['chat_id', 'media'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'reply_parameters'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'media': 'Array of InputMediaAudio , InputMediaDocument , InputMediaLivePhoto , InputMediaPhoto and InputMediaVideo', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'reply_parameters': 'ReplyParameters' } },
  sendLocation: { required: ['chat_id', 'latitude', 'longitude'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'horizontal_accuracy', 'live_period', 'heading', 'proximity_alert_radius', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'latitude': 'Float', 'longitude': 'Float', 'horizontal_accuracy': 'Float', 'live_period': 'Integer', 'heading': 'Integer', 'proximity_alert_radius': 'Integer', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendVenue: { required: ['chat_id', 'latitude', 'longitude', 'title', 'address'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'foursquare_id', 'foursquare_type', 'google_place_id', 'google_place_type', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'latitude': 'Float', 'longitude': 'Float', 'title': 'String', 'address': 'String', 'foursquare_id': 'String', 'foursquare_type': 'String', 'google_place_id': 'String', 'google_place_type': 'String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendContact: { required: ['chat_id', 'phone_number', 'first_name'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'last_name', 'vcard', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'phone_number': 'String', 'first_name': 'String', 'last_name': 'String', 'vcard': 'String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendPoll: { required: ['chat_id', 'question', 'options'], optional: ['business_connection_id', 'message_thread_id', 'question_parse_mode', 'question_entities', 'is_anonymous', 'type', 'allows_multiple_answers', 'allows_revoting', 'shuffle_options', 'allow_adding_options', 'hide_results_until_closes', 'members_only', 'country_codes', 'correct_option_ids', 'explanation', 'explanation_parse_mode', 'explanation_entities', 'explanation_media', 'open_period', 'close_date', 'is_closed', 'description', 'description_parse_mode', 'description_entities', 'media', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'question': 'String', 'question_parse_mode': 'String', 'question_entities': 'Array of MessageEntity', 'options': 'Array of InputPollOption', 'is_anonymous': 'Boolean', 'type': 'String', 'allows_multiple_answers': 'Boolean', 'allows_revoting': 'Boolean', 'shuffle_options': 'Boolean', 'allow_adding_options': 'Boolean', 'hide_results_until_closes': 'Boolean', 'members_only': 'Boolean', 'country_codes': 'Array of String', 'correct_option_ids': 'Array of Integer', 'explanation': 'String', 'explanation_parse_mode': 'String', 'explanation_entities': 'Array of MessageEntity', 'explanation_media': 'InputPollMedia', 'open_period': 'Integer', 'close_date': 'Integer', 'is_closed': 'Boolean', 'description': 'String', 'description_parse_mode': 'String', 'description_entities': 'Array of MessageEntity', 'media': 'InputPollMedia', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendChecklist: { required: ['business_connection_id', 'chat_id', 'checklist'], optional: ['disable_notification', 'protect_content', 'message_effect_id', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'checklist': 'InputChecklist', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'message_effect_id': 'String', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup' } },
  sendDice: { required: ['chat_id'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'emoji', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'emoji': 'String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendMessageDraft: { required: ['chat_id', 'draft_id'], optional: ['message_thread_id', 'text', 'parse_mode', 'entities', 'can_stop', 'keep_on_stop'], types: { 'chat_id': 'Integer', 'message_thread_id': 'Integer', 'draft_id': 'Integer', 'text': 'String', 'parse_mode': 'String', 'entities': 'Array of MessageEntity', 'can_stop': 'Boolean', 'keep_on_stop': 'Boolean' } },
  sendChatAction: { required: ['chat_id', 'action'], optional: ['business_connection_id', 'message_thread_id'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'action': 'String' } },
  setMessageReaction: { required: ['chat_id', 'message_id'], optional: ['reaction', 'is_big'], types: { 'chat_id': 'Integer or String', 'message_id': 'Integer', 'reaction': 'Array of ReactionType', 'is_big': 'Boolean' } },
  getUserProfilePhotos: { required: ['user_id'], optional: ['offset', 'limit'], types: { 'user_id': 'Integer', 'offset': 'Integer', 'limit': 'Integer' } },
  getUserProfileAudios: { required: ['user_id'], optional: ['offset', 'limit'], types: { 'user_id': 'Integer', 'offset': 'Integer', 'limit': 'Integer' } },
  setUserEmojiStatus: { required: ['user_id'], optional: ['emoji_status_custom_emoji_id', 'emoji_status_expiration_date'], types: { 'user_id': 'Integer', 'emoji_status_custom_emoji_id': 'String', 'emoji_status_expiration_date': 'Integer' } },
  getFile: { required: ['file_id'], optional: [], types: { 'file_id': 'String' } },
  banChatMember: { required: ['chat_id', 'user_id'], optional: ['until_date', 'revoke_messages'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'until_date': 'Integer', 'revoke_messages': 'Boolean' } },
  unbanChatMember: { required: ['chat_id', 'user_id'], optional: ['only_if_banned'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'only_if_banned': 'Boolean' } },
  restrictChatMember: { required: ['chat_id', 'user_id', 'permissions'], optional: ['use_independent_chat_permissions', 'until_date'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'permissions': 'ChatPermissions', 'use_independent_chat_permissions': 'Boolean', 'until_date': 'Integer' } },
  promoteChatMember: { required: ['chat_id', 'user_id'], optional: ['is_anonymous', 'can_manage_chat', 'can_delete_messages', 'can_manage_video_chats', 'can_restrict_members', 'can_promote_members', 'can_change_info', 'can_invite_users', 'can_post_stories', 'can_edit_stories', 'can_delete_stories', 'can_post_messages', 'can_edit_messages', 'can_pin_messages', 'can_manage_topics', 'can_manage_direct_messages', 'can_manage_tags', 'can_send_welcome_messages'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'is_anonymous': 'Boolean', 'can_manage_chat': 'Boolean', 'can_delete_messages': 'Boolean', 'can_manage_video_chats': 'Boolean', 'can_restrict_members': 'Boolean', 'can_promote_members': 'Boolean', 'can_change_info': 'Boolean', 'can_invite_users': 'Boolean', 'can_post_stories': 'Boolean', 'can_edit_stories': 'Boolean', 'can_delete_stories': 'Boolean', 'can_post_messages': 'Boolean', 'can_edit_messages': 'Boolean', 'can_pin_messages': 'Boolean', 'can_manage_topics': 'Boolean', 'can_manage_direct_messages': 'Boolean', 'can_manage_tags': 'Boolean', 'can_send_welcome_messages': 'Boolean' } },
  setChatAdministratorCustomTitle: { required: ['chat_id', 'user_id', 'custom_title'], optional: [], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'custom_title': 'String' } },
  setChatMemberTag: { required: ['chat_id', 'user_id'], optional: ['tag'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'tag': 'String' } },
  banChatSenderChat: { required: ['chat_id', 'sender_chat_id'], optional: [], types: { 'chat_id': 'Integer or String', 'sender_chat_id': 'Integer' } },
  unbanChatSenderChat: { required: ['chat_id', 'sender_chat_id'], optional: [], types: { 'chat_id': 'Integer or String', 'sender_chat_id': 'Integer' } },
  setChatPermissions: { required: ['chat_id', 'permissions'], optional: ['use_independent_chat_permissions'], types: { 'chat_id': 'Integer or String', 'permissions': 'ChatPermissions', 'use_independent_chat_permissions': 'Boolean' } },
  exportChatInviteLink: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  createChatInviteLink: { required: ['chat_id'], optional: ['name', 'expire_date', 'member_limit', 'creates_join_request'], types: { 'chat_id': 'Integer or String', 'name': 'String', 'expire_date': 'Integer', 'member_limit': 'Integer', 'creates_join_request': 'Boolean' } },
  editChatInviteLink: { required: ['chat_id', 'invite_link'], optional: ['name', 'expire_date', 'member_limit', 'creates_join_request'], types: { 'chat_id': 'Integer or String', 'invite_link': 'String', 'name': 'String', 'expire_date': 'Integer', 'member_limit': 'Integer', 'creates_join_request': 'Boolean' } },
  createChatSubscriptionInviteLink: { required: ['chat_id', 'subscription_period', 'subscription_price'], optional: ['name'], types: { 'chat_id': 'Integer or String', 'name': 'String', 'subscription_period': 'Integer', 'subscription_price': 'Integer' } },
  editChatSubscriptionInviteLink: { required: ['chat_id', 'invite_link'], optional: ['name'], types: { 'chat_id': 'Integer or String', 'invite_link': 'String', 'name': 'String' } },
  revokeChatInviteLink: { required: ['chat_id', 'invite_link'], optional: [], types: { 'chat_id': 'Integer or String', 'invite_link': 'String' } },
  approveChatJoinRequest: { required: ['chat_id', 'user_id'], optional: [], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer' } },
  declineChatJoinRequest: { required: ['chat_id', 'user_id'], optional: [], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer' } },
  answerChatJoinRequestQuery: { required: ['chat_join_request_query_id', 'result'], optional: [], types: { 'chat_join_request_query_id': 'String', 'result': 'String' } },
  sendChatJoinRequestWebApp: { required: ['chat_join_request_query_id', 'web_app_url'], optional: [], types: { 'chat_join_request_query_id': 'String', 'web_app_url': 'String' } },
  setChatPhoto: { required: ['chat_id', 'photo'], optional: [], types: { 'chat_id': 'Integer or String', 'photo': 'InputFile' } },
  deleteChatPhoto: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  setChatTitle: { required: ['chat_id', 'title'], optional: [], types: { 'chat_id': 'Integer or String', 'title': 'String' } },
  setChatDescription: { required: ['chat_id'], optional: ['description'], types: { 'chat_id': 'Integer or String', 'description': 'String' } },
  pinChatMessage: { required: ['chat_id', 'message_id'], optional: ['business_connection_id', 'disable_notification'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'disable_notification': 'Boolean' } },
  unpinChatMessage: { required: ['chat_id'], optional: ['business_connection_id', 'message_id'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer' } },
  unpinAllChatMessages: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  leaveChat: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  getChat: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  getChatAdministrators: { required: ['chat_id'], optional: ['return_bots'], types: { 'chat_id': 'Integer or String', 'return_bots': 'Boolean' } },
  getChatMemberCount: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  getChatMember: { required: ['chat_id', 'user_id'], optional: [], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer' } },
  getUserPersonalChatMessages: { required: ['user_id', 'limit'], optional: [], types: { 'user_id': 'Integer', 'limit': 'Integer' } },
  setChatStickerSet: { required: ['chat_id', 'sticker_set_name'], optional: [], types: { 'chat_id': 'Integer or String', 'sticker_set_name': 'String' } },
  deleteChatStickerSet: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  getForumTopicIconStickers: { required: [], optional: [], types: {  } },
  createForumTopic: { required: ['chat_id', 'name'], optional: ['icon_color', 'icon_custom_emoji_id'], types: { 'chat_id': 'Integer or String', 'name': 'String', 'icon_color': 'Integer', 'icon_custom_emoji_id': 'String' } },
  editForumTopic: { required: ['chat_id', 'message_thread_id'], optional: ['name', 'icon_custom_emoji_id'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'name': 'String', 'icon_custom_emoji_id': 'String' } },
  closeForumTopic: { required: ['chat_id', 'message_thread_id'], optional: [], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer' } },
  reopenForumTopic: { required: ['chat_id', 'message_thread_id'], optional: [], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer' } },
  deleteForumTopic: { required: ['chat_id', 'message_thread_id'], optional: [], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer' } },
  unpinAllForumTopicMessages: { required: ['chat_id', 'message_thread_id'], optional: [], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer' } },
  editGeneralForumTopic: { required: ['chat_id', 'name'], optional: [], types: { 'chat_id': 'Integer or String', 'name': 'String' } },
  closeGeneralForumTopic: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  reopenGeneralForumTopic: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  hideGeneralForumTopic: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  unhideGeneralForumTopic: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  unpinAllGeneralForumTopicMessages: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  answerCallbackQuery: { required: ['callback_query_id'], optional: ['text', 'show_alert', 'url', 'cache_time'], types: { 'callback_query_id': 'String', 'text': 'String', 'show_alert': 'Boolean', 'url': 'String', 'cache_time': 'Integer' } },
  answerGuestQuery: { required: ['guest_query_id', 'result'], optional: [], types: { 'guest_query_id': 'String', 'result': 'InlineQueryResult' } },
  getUserChatBoosts: { required: ['chat_id', 'user_id'], optional: [], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer' } },
  getBusinessConnection: { required: ['business_connection_id'], optional: [], types: { 'business_connection_id': 'String' } },
  getManagedBotToken: { required: ['user_id'], optional: [], types: { 'user_id': 'Integer' } },
  replaceManagedBotToken: { required: ['user_id'], optional: [], types: { 'user_id': 'Integer' } },
  getManagedBotAccessSettings: { required: ['user_id'], optional: [], types: { 'user_id': 'Integer' } },
  setManagedBotAccessSettings: { required: ['user_id', 'is_access_restricted'], optional: ['added_user_ids'], types: { 'user_id': 'Integer', 'is_access_restricted': 'Boolean', 'added_user_ids': 'Array of Integer' } },
  setMyCommands: { required: ['commands'], optional: ['scope', 'language_code'], types: { 'commands': 'Array of BotCommand', 'scope': 'BotCommandScope', 'language_code': 'String' } },
  deleteMyCommands: { required: [], optional: ['scope', 'language_code'], types: { 'scope': 'BotCommandScope', 'language_code': 'String' } },
  getMyCommands: { required: [], optional: ['scope', 'language_code'], types: { 'scope': 'BotCommandScope', 'language_code': 'String' } },
  setMyName: { required: [], optional: ['name', 'language_code'], types: { 'name': 'String', 'language_code': 'String' } },
  getMyName: { required: [], optional: ['language_code'], types: { 'language_code': 'String' } },
  setMyDescription: { required: [], optional: ['description', 'language_code'], types: { 'description': 'String', 'language_code': 'String' } },
  getMyDescription: { required: [], optional: ['language_code'], types: { 'language_code': 'String' } },
  setMyShortDescription: { required: [], optional: ['short_description', 'language_code'], types: { 'short_description': 'String', 'language_code': 'String' } },
  getMyShortDescription: { required: [], optional: ['language_code'], types: { 'language_code': 'String' } },
  setMyProfilePhoto: { required: ['photo'], optional: [], types: { 'photo': 'InputProfilePhoto' } },
  removeMyProfilePhoto: { required: [], optional: [], types: {  } },
  setChatMenuButton: { required: [], optional: ['chat_id', 'menu_button'], types: { 'chat_id': 'Integer', 'menu_button': 'MenuButton' } },
  getChatMenuButton: { required: [], optional: ['chat_id'], types: { 'chat_id': 'Integer' } },
  setMyDefaultAdministratorRights: { required: [], optional: ['rights', 'for_channels'], types: { 'rights': 'ChatAdministratorRights', 'for_channels': 'Boolean' } },
  getMyDefaultAdministratorRights: { required: [], optional: ['for_channels'], types: { 'for_channels': 'Boolean' } },
  getAvailableGifts: { required: [], optional: [], types: {  } },
  sendGift: { required: ['gift_id'], optional: ['user_id', 'chat_id', 'pay_for_upgrade', 'text', 'text_parse_mode', 'text_entities'], types: { 'user_id': 'Integer', 'chat_id': 'Integer or String', 'gift_id': 'String', 'pay_for_upgrade': 'Boolean', 'text': 'String', 'text_parse_mode': 'String', 'text_entities': 'Array of MessageEntity' } },
  giftPremiumSubscription: { required: ['user_id', 'month_count', 'star_count'], optional: ['text', 'text_parse_mode', 'text_entities'], types: { 'user_id': 'Integer', 'month_count': 'Integer', 'star_count': 'Integer', 'text': 'String', 'text_parse_mode': 'String', 'text_entities': 'Array of MessageEntity' } },
  verifyUser: { required: ['user_id'], optional: ['custom_description'], types: { 'user_id': 'Integer', 'custom_description': 'String' } },
  verifyChat: { required: ['chat_id'], optional: ['custom_description'], types: { 'chat_id': 'Integer or String', 'custom_description': 'String' } },
  removeUserVerification: { required: ['user_id'], optional: [], types: { 'user_id': 'Integer' } },
  removeChatVerification: { required: ['chat_id'], optional: [], types: { 'chat_id': 'Integer or String' } },
  readBusinessMessage: { required: ['business_connection_id', 'chat_id', 'message_id'], optional: [], types: { 'business_connection_id': 'String', 'chat_id': 'Integer', 'message_id': 'Integer' } },
  deleteBusinessMessages: { required: ['business_connection_id', 'message_ids'], optional: [], types: { 'business_connection_id': 'String', 'message_ids': 'Array of Integer' } },
  setBusinessAccountName: { required: ['business_connection_id', 'first_name'], optional: ['last_name'], types: { 'business_connection_id': 'String', 'first_name': 'String', 'last_name': 'String' } },
  setBusinessAccountUsername: { required: ['business_connection_id'], optional: ['username'], types: { 'business_connection_id': 'String', 'username': 'String' } },
  setBusinessAccountBio: { required: ['business_connection_id'], optional: ['bio'], types: { 'business_connection_id': 'String', 'bio': 'String' } },
  setBusinessAccountProfilePhoto: { required: ['business_connection_id', 'photo'], optional: ['is_public'], types: { 'business_connection_id': 'String', 'photo': 'InputProfilePhoto', 'is_public': 'Boolean' } },
  removeBusinessAccountProfilePhoto: { required: ['business_connection_id'], optional: ['is_public'], types: { 'business_connection_id': 'String', 'is_public': 'Boolean' } },
  setBusinessAccountGiftSettings: { required: ['business_connection_id', 'show_gift_button', 'accepted_gift_types'], optional: [], types: { 'business_connection_id': 'String', 'show_gift_button': 'Boolean', 'accepted_gift_types': 'AcceptedGiftTypes' } },
  getBusinessAccountStarBalance: { required: ['business_connection_id'], optional: [], types: { 'business_connection_id': 'String' } },
  transferBusinessAccountStars: { required: ['business_connection_id', 'star_count'], optional: [], types: { 'business_connection_id': 'String', 'star_count': 'Integer' } },
  getBusinessAccountGifts: { required: ['business_connection_id'], optional: ['exclude_unsaved', 'exclude_saved', 'exclude_unlimited', 'exclude_limited_upgradable', 'exclude_limited_non_upgradable', 'exclude_unique', 'exclude_from_blockchain', 'sort_by_price', 'offset', 'limit'], types: { 'business_connection_id': 'String', 'exclude_unsaved': 'Boolean', 'exclude_saved': 'Boolean', 'exclude_unlimited': 'Boolean', 'exclude_limited_upgradable': 'Boolean', 'exclude_limited_non_upgradable': 'Boolean', 'exclude_unique': 'Boolean', 'exclude_from_blockchain': 'Boolean', 'sort_by_price': 'Boolean', 'offset': 'String', 'limit': 'Integer' } },
  getUserGifts: { required: ['user_id'], optional: ['exclude_unlimited', 'exclude_limited_upgradable', 'exclude_limited_non_upgradable', 'exclude_from_blockchain', 'exclude_unique', 'sort_by_price', 'offset', 'limit'], types: { 'user_id': 'Integer', 'exclude_unlimited': 'Boolean', 'exclude_limited_upgradable': 'Boolean', 'exclude_limited_non_upgradable': 'Boolean', 'exclude_from_blockchain': 'Boolean', 'exclude_unique': 'Boolean', 'sort_by_price': 'Boolean', 'offset': 'String', 'limit': 'Integer' } },
  getChatGifts: { required: ['chat_id'], optional: ['exclude_unsaved', 'exclude_saved', 'exclude_unlimited', 'exclude_limited_upgradable', 'exclude_limited_non_upgradable', 'exclude_from_blockchain', 'exclude_unique', 'sort_by_price', 'offset', 'limit'], types: { 'chat_id': 'Integer or String', 'exclude_unsaved': 'Boolean', 'exclude_saved': 'Boolean', 'exclude_unlimited': 'Boolean', 'exclude_limited_upgradable': 'Boolean', 'exclude_limited_non_upgradable': 'Boolean', 'exclude_from_blockchain': 'Boolean', 'exclude_unique': 'Boolean', 'sort_by_price': 'Boolean', 'offset': 'String', 'limit': 'Integer' } },
  convertGiftToStars: { required: ['business_connection_id', 'owned_gift_id'], optional: [], types: { 'business_connection_id': 'String', 'owned_gift_id': 'String' } },
  upgradeGift: { required: ['business_connection_id', 'owned_gift_id'], optional: ['keep_original_details', 'star_count'], types: { 'business_connection_id': 'String', 'owned_gift_id': 'String', 'keep_original_details': 'Boolean', 'star_count': 'Integer' } },
  transferGift: { required: ['business_connection_id', 'owned_gift_id', 'new_owner_chat_id'], optional: ['star_count'], types: { 'business_connection_id': 'String', 'owned_gift_id': 'String', 'new_owner_chat_id': 'Integer', 'star_count': 'Integer' } },
  postStory: { required: ['business_connection_id', 'content', 'active_period'], optional: ['caption', 'parse_mode', 'caption_entities', 'areas', 'post_to_chat_page', 'protect_content'], types: { 'business_connection_id': 'String', 'content': 'InputStoryContent', 'active_period': 'Integer', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'areas': 'Array of StoryArea', 'post_to_chat_page': 'Boolean', 'protect_content': 'Boolean' } },
  repostStory: { required: ['business_connection_id', 'from_chat_id', 'from_story_id', 'active_period'], optional: ['post_to_chat_page', 'protect_content'], types: { 'business_connection_id': 'String', 'from_chat_id': 'Integer', 'from_story_id': 'Integer', 'active_period': 'Integer', 'post_to_chat_page': 'Boolean', 'protect_content': 'Boolean' } },
  editStory: { required: ['business_connection_id', 'story_id', 'content'], optional: ['caption', 'parse_mode', 'caption_entities', 'areas'], types: { 'business_connection_id': 'String', 'story_id': 'Integer', 'content': 'InputStoryContent', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'areas': 'Array of StoryArea' } },
  deleteStory: { required: ['business_connection_id', 'story_id'], optional: [], types: { 'business_connection_id': 'String', 'story_id': 'Integer' } },
  answerWebAppQuery: { required: ['web_app_query_id', 'result'], optional: [], types: { 'web_app_query_id': 'String', 'result': 'InlineQueryResult' } },
  savePreparedInlineMessage: { required: ['user_id', 'result'], optional: ['allow_user_chats', 'allow_bot_chats', 'allow_group_chats', 'allow_channel_chats'], types: { 'user_id': 'Integer', 'result': 'InlineQueryResult', 'allow_user_chats': 'Boolean', 'allow_bot_chats': 'Boolean', 'allow_group_chats': 'Boolean', 'allow_channel_chats': 'Boolean' } },
  savePreparedKeyboardButton: { required: ['user_id', 'button'], optional: [], types: { 'user_id': 'Integer', 'button': 'KeyboardButton' } },
  editMessageText: { required: [], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'text', 'parse_mode', 'entities', 'link_preview_options', 'rich_message', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'text': 'String', 'parse_mode': 'String', 'entities': 'Array of MessageEntity', 'link_preview_options': 'LinkPreviewOptions', 'rich_message': 'InputRichMessage', 'reply_markup': 'InlineKeyboardMarkup' } },
  editMessageCaption: { required: [], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'reply_markup': 'InlineKeyboardMarkup' } },
  editMessageMedia: { required: ['media'], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'media': 'InputMedia', 'reply_markup': 'InlineKeyboardMarkup' } },
  editMessageLiveLocation: { required: ['latitude', 'longitude'], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'live_period', 'horizontal_accuracy', 'heading', 'proximity_alert_radius', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'latitude': 'Float', 'longitude': 'Float', 'live_period': 'Integer', 'horizontal_accuracy': 'Float', 'heading': 'Integer', 'proximity_alert_radius': 'Integer', 'reply_markup': 'InlineKeyboardMarkup' } },
  stopMessageLiveLocation: { required: [], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'reply_markup': 'InlineKeyboardMarkup' } },
  editMessageChecklist: { required: ['business_connection_id', 'chat_id', 'message_id', 'checklist'], optional: ['reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'checklist': 'InputChecklist', 'reply_markup': 'InlineKeyboardMarkup' } },
  editMessageReplyMarkup: { required: [], optional: ['business_connection_id', 'chat_id', 'message_id', 'inline_message_id', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'inline_message_id': 'String', 'reply_markup': 'InlineKeyboardMarkup' } },
  stopPoll: { required: ['chat_id', 'message_id'], optional: ['business_connection_id', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_id': 'Integer', 'reply_markup': 'InlineKeyboardMarkup' } },
  editEphemeralMessageText: { required: ['chat_id', 'receiver_user_id', 'ephemeral_message_id'], optional: ['text', 'parse_mode', 'entities', 'rich_message', 'link_preview_options', 'reply_markup'], types: { 'chat_id': 'Integer or String', 'receiver_user_id': 'Integer', 'ephemeral_message_id': 'Integer', 'text': 'String', 'parse_mode': 'String', 'entities': 'Array of MessageEntity', 'rich_message': 'InputRichMessage', 'link_preview_options': 'LinkPreviewOptions', 'reply_markup': 'InlineKeyboardMarkup' } },
  editEphemeralMessageMedia: { required: ['chat_id', 'receiver_user_id', 'ephemeral_message_id', 'media'], optional: ['reply_markup'], types: { 'chat_id': 'Integer or String', 'receiver_user_id': 'Integer', 'ephemeral_message_id': 'Integer', 'media': 'InputMedia', 'reply_markup': 'InlineKeyboardMarkup' } },
  editEphemeralMessageCaption: { required: ['chat_id', 'receiver_user_id', 'ephemeral_message_id'], optional: ['caption', 'parse_mode', 'caption_entities', 'show_caption_above_media', 'reply_markup'], types: { 'chat_id': 'Integer or String', 'receiver_user_id': 'Integer', 'ephemeral_message_id': 'Integer', 'caption': 'String', 'parse_mode': 'String', 'caption_entities': 'Array of MessageEntity', 'show_caption_above_media': 'Boolean', 'reply_markup': 'InlineKeyboardMarkup' } },
  editEphemeralMessageReplyMarkup: { required: ['chat_id', 'receiver_user_id', 'ephemeral_message_id'], optional: ['reply_markup'], types: { 'chat_id': 'Integer or String', 'receiver_user_id': 'Integer', 'ephemeral_message_id': 'Integer', 'reply_markup': 'InlineKeyboardMarkup' } },
  approveSuggestedPost: { required: ['chat_id', 'message_id'], optional: ['send_date'], types: { 'chat_id': 'Integer', 'message_id': 'Integer', 'send_date': 'Integer' } },
  declineSuggestedPost: { required: ['chat_id', 'message_id'], optional: ['comment'], types: { 'chat_id': 'Integer', 'message_id': 'Integer', 'comment': 'String' } },
  deleteMessage: { required: ['chat_id', 'message_id'], optional: [], types: { 'chat_id': 'Integer or String', 'message_id': 'Integer' } },
  deleteMessages: { required: ['chat_id', 'message_ids'], optional: [], types: { 'chat_id': 'Integer or String', 'message_ids': 'Array of Integer' } },
  deleteEphemeralMessage: { required: ['chat_id', 'receiver_user_id', 'ephemeral_message_id'], optional: [], types: { 'chat_id': 'Integer or String', 'receiver_user_id': 'Integer', 'ephemeral_message_id': 'Integer' } },
  deleteMessageReaction: { required: ['chat_id', 'message_id'], optional: ['user_id', 'actor_chat_id'], types: { 'chat_id': 'Integer or String', 'message_id': 'Integer', 'user_id': 'Integer', 'actor_chat_id': 'Integer' } },
  deleteAllMessageReactions: { required: ['chat_id'], optional: ['user_id', 'actor_chat_id'], types: { 'chat_id': 'Integer or String', 'user_id': 'Integer', 'actor_chat_id': 'Integer' } },
  sendSticker: { required: ['chat_id', 'sticker'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'emoji', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'sticker': 'InputFile or String', 'emoji': 'String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  getStickerSet: { required: ['name'], optional: [], types: { 'name': 'String' } },
  getCustomEmojiStickers: { required: ['custom_emoji_ids'], optional: [], types: { 'custom_emoji_ids': 'Array of String' } },
  uploadStickerFile: { required: ['user_id', 'sticker', 'sticker_format'], optional: [], types: { 'user_id': 'Integer', 'sticker': 'InputFile', 'sticker_format': 'String' } },
  createNewStickerSet: { required: ['user_id', 'name', 'title', 'stickers'], optional: ['sticker_type', 'needs_repainting'], types: { 'user_id': 'Integer', 'name': 'String', 'title': 'String', 'stickers': 'Array of InputSticker', 'sticker_type': 'String', 'needs_repainting': 'Boolean' } },
  addStickerToSet: { required: ['user_id', 'name', 'sticker'], optional: [], types: { 'user_id': 'Integer', 'name': 'String', 'sticker': 'InputSticker' } },
  setStickerPositionInSet: { required: ['sticker', 'position'], optional: [], types: { 'sticker': 'String', 'position': 'Integer' } },
  deleteStickerFromSet: { required: ['sticker'], optional: [], types: { 'sticker': 'String' } },
  replaceStickerInSet: { required: ['user_id', 'name', 'old_sticker', 'sticker'], optional: [], types: { 'user_id': 'Integer', 'name': 'String', 'old_sticker': 'String', 'sticker': 'InputSticker' } },
  setStickerEmojiList: { required: ['sticker', 'emoji_list'], optional: [], types: { 'sticker': 'String', 'emoji_list': 'Array of String' } },
  setStickerKeywords: { required: ['sticker'], optional: ['keywords'], types: { 'sticker': 'String', 'keywords': 'Array of String' } },
  setStickerMaskPosition: { required: ['sticker'], optional: ['mask_position'], types: { 'sticker': 'String', 'mask_position': 'MaskPosition' } },
  setStickerSetTitle: { required: ['name', 'title'], optional: [], types: { 'name': 'String', 'title': 'String' } },
  setStickerSetThumbnail: { required: ['name', 'user_id', 'format'], optional: ['thumbnail'], types: { 'name': 'String', 'user_id': 'Integer', 'thumbnail': 'InputFile or String', 'format': 'String' } },
  setCustomEmojiStickerSetThumbnail: { required: ['name'], optional: ['custom_emoji_id'], types: { 'name': 'String', 'custom_emoji_id': 'String' } },
  deleteStickerSet: { required: ['name'], optional: [], types: { 'name': 'String' } },
  sendRichMessage: { required: ['chat_id', 'rich_message'], optional: ['business_connection_id', 'message_thread_id', 'direct_messages_topic_id', 'ephemeral_message_parameters', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'ephemeral_message_parameters': 'EphemeralMessageParameters', 'rich_message': 'InputRichMessage', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup or ReplyKeyboardMarkup or ReplyKeyboardRemove or ForceReply' } },
  sendRichMessageDraft: { required: ['chat_id', 'draft_id', 'rich_message'], optional: ['message_thread_id', 'can_stop', 'keep_on_stop'], types: { 'chat_id': 'Integer', 'message_thread_id': 'Integer', 'draft_id': 'Integer', 'rich_message': 'InputRichMessage', 'can_stop': 'Boolean', 'keep_on_stop': 'Boolean' } },
  answerInlineQuery: { required: ['inline_query_id', 'results'], optional: ['cache_time', 'is_personal', 'next_offset', 'button'], types: { 'inline_query_id': 'String', 'results': 'Array of InlineQueryResult', 'cache_time': 'Integer', 'is_personal': 'Boolean', 'next_offset': 'String', 'button': 'InlineQueryResultsButton' } },
  sendInvoice: { required: ['chat_id', 'title', 'description', 'payload', 'currency', 'prices'], optional: ['message_thread_id', 'direct_messages_topic_id', 'provider_token', 'max_tip_amount', 'suggested_tip_amounts', 'start_parameter', 'provider_data', 'photo_url', 'photo_size', 'photo_width', 'photo_height', 'need_name', 'need_phone_number', 'need_email', 'need_shipping_address', 'send_phone_number_to_provider', 'send_email_to_provider', 'is_flexible', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'suggested_post_parameters', 'reply_parameters', 'reply_markup'], types: { 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'direct_messages_topic_id': 'Integer', 'title': 'String', 'description': 'String', 'payload': 'String', 'provider_token': 'String', 'currency': 'String', 'prices': 'Array of LabeledPrice', 'max_tip_amount': 'Integer', 'suggested_tip_amounts': 'Array of Integer', 'start_parameter': 'String', 'provider_data': 'String', 'photo_url': 'String', 'photo_size': 'Integer', 'photo_width': 'Integer', 'photo_height': 'Integer', 'need_name': 'Boolean', 'need_phone_number': 'Boolean', 'need_email': 'Boolean', 'need_shipping_address': 'Boolean', 'send_phone_number_to_provider': 'Boolean', 'send_email_to_provider': 'Boolean', 'is_flexible': 'Boolean', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'suggested_post_parameters': 'SuggestedPostParameters', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup' } },
  createInvoiceLink: { required: ['title', 'description', 'payload', 'currency', 'prices'], optional: ['business_connection_id', 'provider_token', 'subscription_period', 'max_tip_amount', 'suggested_tip_amounts', 'provider_data', 'photo_url', 'photo_size', 'photo_width', 'photo_height', 'need_name', 'need_phone_number', 'need_email', 'need_shipping_address', 'send_phone_number_to_provider', 'send_email_to_provider', 'is_flexible'], types: { 'business_connection_id': 'String', 'title': 'String', 'description': 'String', 'payload': 'String', 'provider_token': 'String', 'currency': 'String', 'prices': 'Array of LabeledPrice', 'subscription_period': 'Integer', 'max_tip_amount': 'Integer', 'suggested_tip_amounts': 'Array of Integer', 'provider_data': 'String', 'photo_url': 'String', 'photo_size': 'Integer', 'photo_width': 'Integer', 'photo_height': 'Integer', 'need_name': 'Boolean', 'need_phone_number': 'Boolean', 'need_email': 'Boolean', 'need_shipping_address': 'Boolean', 'send_phone_number_to_provider': 'Boolean', 'send_email_to_provider': 'Boolean', 'is_flexible': 'Boolean' } },
  answerShippingQuery: { required: ['shipping_query_id', 'ok'], optional: ['shipping_options', 'error_message'], types: { 'shipping_query_id': 'String', 'ok': 'Boolean', 'shipping_options': 'Array of ShippingOption', 'error_message': 'String' } },
  answerPreCheckoutQuery: { required: ['pre_checkout_query_id', 'ok'], optional: ['error_message'], types: { 'pre_checkout_query_id': 'String', 'ok': 'Boolean', 'error_message': 'String' } },
  getMyStarBalance: { required: [], optional: [], types: {  } },
  getStarTransactions: { required: [], optional: ['offset', 'limit'], types: { 'offset': 'Integer', 'limit': 'Integer' } },
  refundStarPayment: { required: ['user_id', 'telegram_payment_charge_id'], optional: [], types: { 'user_id': 'Integer', 'telegram_payment_charge_id': 'String' } },
  editUserStarSubscription: { required: ['user_id', 'telegram_payment_charge_id', 'is_canceled'], optional: [], types: { 'user_id': 'Integer', 'telegram_payment_charge_id': 'String', 'is_canceled': 'Boolean' } },
  setPassportDataErrors: { required: ['user_id', 'errors'], optional: [], types: { 'user_id': 'Integer', 'errors': 'Array of PassportElementError' } },
  sendGame: { required: ['chat_id', 'game_short_name'], optional: ['business_connection_id', 'message_thread_id', 'disable_notification', 'protect_content', 'allow_paid_broadcast', 'message_effect_id', 'reply_parameters', 'reply_markup'], types: { 'business_connection_id': 'String', 'chat_id': 'Integer or String', 'message_thread_id': 'Integer', 'game_short_name': 'String', 'disable_notification': 'Boolean', 'protect_content': 'Boolean', 'allow_paid_broadcast': 'Boolean', 'message_effect_id': 'String', 'reply_parameters': 'ReplyParameters', 'reply_markup': 'InlineKeyboardMarkup' } },
  setGameScore: { required: ['user_id', 'score'], optional: ['force', 'disable_edit_message', 'chat_id', 'message_id', 'inline_message_id'], types: { 'user_id': 'Integer', 'score': 'Integer', 'force': 'Boolean', 'disable_edit_message': 'Boolean', 'chat_id': 'Integer', 'message_id': 'Integer', 'inline_message_id': 'String' } },
  getGameHighScores: { required: ['user_id'], optional: ['chat_id', 'message_id', 'inline_message_id'], types: { 'user_id': 'Integer', 'chat_id': 'Integer', 'message_id': 'Integer', 'inline_message_id': 'String' } },
} as const;

export const TELEGRAM_METHOD_RESULT_SPEC = {
  getUpdates: 'Array of Update',
  setWebhook: 'Boolean',
  deleteWebhook: 'Boolean',
  getWebhookInfo: 'WebhookInfo',
  getMe: 'User',
  logOut: 'Boolean',
  close: 'Boolean',
  sendMessage: 'Message',
  forwardMessage: 'Message',
  forwardMessages: 'Array of MessageId',
  copyMessage: 'MessageId',
  copyMessages: 'Array of MessageId',
  sendPhoto: 'Message',
  sendLivePhoto: 'Message',
  sendAudio: 'Message',
  sendDocument: 'Message',
  sendVideo: 'Message',
  sendAnimation: 'Message',
  sendVoice: 'Message',
  sendVideoNote: 'Message',
  sendPaidMedia: 'Message',
  sendMediaGroup: 'Array of Message',
  sendLocation: 'Message',
  sendVenue: 'Message',
  sendContact: 'Message',
  sendPoll: 'Message',
  sendChecklist: 'Message',
  sendDice: 'Message',
  sendMessageDraft: 'Boolean',
  sendChatAction: 'Boolean',
  setMessageReaction: 'Boolean',
  getUserProfilePhotos: 'UserProfilePhotos',
  getUserProfileAudios: 'UserProfileAudios',
  setUserEmojiStatus: 'Boolean',
  getFile: 'File',
  banChatMember: 'Boolean',
  unbanChatMember: 'Boolean',
  restrictChatMember: 'Boolean',
  promoteChatMember: 'Boolean',
  setChatAdministratorCustomTitle: 'Boolean',
  setChatMemberTag: 'Boolean',
  banChatSenderChat: 'Boolean',
  unbanChatSenderChat: 'Boolean',
  setChatPermissions: 'Boolean',
  exportChatInviteLink: 'String',
  createChatInviteLink: 'ChatInviteLink',
  editChatInviteLink: 'ChatInviteLink',
  createChatSubscriptionInviteLink: 'ChatInviteLink',
  editChatSubscriptionInviteLink: 'ChatInviteLink',
  revokeChatInviteLink: 'ChatInviteLink',
  approveChatJoinRequest: 'Boolean',
  declineChatJoinRequest: 'Boolean',
  answerChatJoinRequestQuery: 'Boolean',
  sendChatJoinRequestWebApp: 'Boolean',
  setChatPhoto: 'Boolean',
  deleteChatPhoto: 'Boolean',
  setChatTitle: 'Boolean',
  setChatDescription: 'Boolean',
  pinChatMessage: 'Boolean',
  unpinChatMessage: 'Boolean',
  unpinAllChatMessages: 'Boolean',
  leaveChat: 'Boolean',
  getChat: 'ChatFullInfo',
  getChatAdministrators: 'Array of ChatMember',
  getChatMemberCount: 'Integer',
  getChatMember: 'ChatMember',
  getUserPersonalChatMessages: 'Array of Message',
  setChatStickerSet: 'Boolean',
  deleteChatStickerSet: 'Boolean',
  getForumTopicIconStickers: 'Array of Sticker',
  createForumTopic: 'ForumTopic',
  editForumTopic: 'Boolean',
  closeForumTopic: 'Boolean',
  reopenForumTopic: 'Boolean',
  deleteForumTopic: 'Boolean',
  unpinAllForumTopicMessages: 'Boolean',
  editGeneralForumTopic: 'Boolean',
  closeGeneralForumTopic: 'Boolean',
  reopenGeneralForumTopic: 'Boolean',
  hideGeneralForumTopic: 'Boolean',
  unhideGeneralForumTopic: 'Boolean',
  unpinAllGeneralForumTopicMessages: 'Boolean',
  answerCallbackQuery: 'Boolean',
  answerGuestQuery: 'SentGuestMessage',
  getUserChatBoosts: 'UserChatBoosts',
  getBusinessConnection: 'BusinessConnection',
  getManagedBotToken: 'String',
  replaceManagedBotToken: 'String',
  getManagedBotAccessSettings: 'BotAccessSettings',
  setManagedBotAccessSettings: 'Boolean',
  setMyCommands: 'Boolean',
  deleteMyCommands: 'Boolean',
  getMyCommands: 'Array of BotCommand',
  setMyName: 'Boolean',
  getMyName: 'BotName',
  setMyDescription: 'Boolean',
  getMyDescription: 'BotDescription',
  setMyShortDescription: 'Boolean',
  getMyShortDescription: 'BotShortDescription',
  setMyProfilePhoto: 'Boolean',
  removeMyProfilePhoto: 'Boolean',
  setChatMenuButton: 'Boolean',
  getChatMenuButton: 'MenuButton',
  setMyDefaultAdministratorRights: 'Boolean',
  getMyDefaultAdministratorRights: 'ChatAdministratorRights',
  getAvailableGifts: 'Gifts',
  sendGift: 'Boolean',
  giftPremiumSubscription: 'Boolean',
  verifyUser: 'Boolean',
  verifyChat: 'Boolean',
  removeUserVerification: 'Boolean',
  removeChatVerification: 'Boolean',
  readBusinessMessage: 'Boolean',
  deleteBusinessMessages: 'Boolean',
  setBusinessAccountName: 'Boolean',
  setBusinessAccountUsername: 'Boolean',
  setBusinessAccountBio: 'Boolean',
  setBusinessAccountProfilePhoto: 'Boolean',
  removeBusinessAccountProfilePhoto: 'Boolean',
  setBusinessAccountGiftSettings: 'Boolean',
  getBusinessAccountStarBalance: 'StarAmount',
  transferBusinessAccountStars: 'Boolean',
  getBusinessAccountGifts: 'OwnedGifts',
  getUserGifts: 'OwnedGifts',
  getChatGifts: 'OwnedGifts',
  convertGiftToStars: 'Boolean',
  upgradeGift: 'Boolean',
  transferGift: 'Boolean',
  postStory: 'Story',
  repostStory: 'Story',
  editStory: 'Story',
  deleteStory: 'Boolean',
  answerWebAppQuery: 'SentWebAppMessage',
  savePreparedInlineMessage: 'PreparedInlineMessage',
  savePreparedKeyboardButton: 'PreparedKeyboardButton',
  editMessageText: 'Message | Boolean',
  editMessageCaption: 'Message | Boolean',
  editMessageMedia: 'Message | Boolean',
  editMessageLiveLocation: 'Message | Boolean',
  stopMessageLiveLocation: 'Message | Boolean',
  editMessageChecklist: 'Message',
  editMessageReplyMarkup: 'Message | Boolean',
  stopPoll: 'Poll',
  editEphemeralMessageText: 'Boolean',
  editEphemeralMessageMedia: 'Boolean',
  editEphemeralMessageCaption: 'Boolean',
  editEphemeralMessageReplyMarkup: 'Boolean',
  approveSuggestedPost: 'Boolean',
  declineSuggestedPost: 'Boolean',
  deleteMessage: 'Boolean',
  deleteMessages: 'Boolean',
  deleteEphemeralMessage: 'Boolean',
  deleteMessageReaction: 'Boolean',
  deleteAllMessageReactions: 'Boolean',
  sendSticker: 'Message',
  getStickerSet: 'StickerSet',
  getCustomEmojiStickers: 'Array of Sticker',
  uploadStickerFile: 'File',
  createNewStickerSet: 'Boolean',
  addStickerToSet: 'Boolean',
  setStickerPositionInSet: 'Boolean',
  deleteStickerFromSet: 'Boolean',
  replaceStickerInSet: 'Boolean',
  setStickerEmojiList: 'Boolean',
  setStickerKeywords: 'Boolean',
  setStickerMaskPosition: 'Boolean',
  setStickerSetTitle: 'Boolean',
  setStickerSetThumbnail: 'Boolean',
  setCustomEmojiStickerSetThumbnail: 'Boolean',
  deleteStickerSet: 'Boolean',
  sendRichMessage: 'Message',
  sendRichMessageDraft: 'Boolean',
  answerInlineQuery: 'Boolean',
  sendInvoice: 'Message',
  createInvoiceLink: 'String',
  answerShippingQuery: 'Boolean',
  answerPreCheckoutQuery: 'Boolean',
  getMyStarBalance: 'StarAmount',
  getStarTransactions: 'StarTransactions',
  refundStarPayment: 'Boolean',
  editUserStarSubscription: 'Boolean',
  setPassportDataErrors: 'Boolean',
  sendGame: 'Message',
  setGameScore: 'Message | Boolean',
  getGameHighScores: 'Array of GameHighScore',
} as const;

type TelegramDocParameterType<T extends string> =
  T extends 'String' ? string :
  T extends 'Integer' | 'Float' ? number :
  T extends 'Boolean' ? boolean :
  T extends 'Integer or String' ? number | string :
  T extends 'InputFile' | 'InputFile or String' ? TelegramBotApiInputFile :
  T extends 'Array of InputMediaAudio , InputMediaDocument , InputMediaLivePhoto , InputMediaPhoto and InputMediaVideo'
    ? Array<TelegramBotApiType<'InputMediaAudio'> | TelegramBotApiType<'InputMediaDocument'> | TelegramBotApiType<'InputMediaLivePhoto'> | TelegramBotApiType<'InputMediaPhoto'> | TelegramBotApiType<'InputMediaVideo'>> :
  T extends `Array of ${infer Item}` ? Array<TelegramDocParameterType<Item>> :
  T extends `${infer Left} or ${infer Right}` ? TelegramDocParameterType<Left> | TelegramDocParameterType<Right> :
  TelegramBotApiType<T>;

type TelegramParameterSpec = typeof TELEGRAM_METHOD_PARAMETER_SPEC;
type TelegramParamsFromSpec<S extends { required: readonly string[]; optional: readonly string[]; types: Record<string, string> }> =
  [S['required'][number] | S['optional'][number]] extends [never]
    ? Record<string, never>
    : { [K in S['required'][number]]: K extends keyof S['types'] ? TelegramDocParameterType<S['types'][K]> : unknown }
      & { [K in S['optional'][number]]?: K extends keyof S['types'] ? TelegramDocParameterType<S['types'][K]> : unknown };

export type TelegramGeneratedMethodParams = {
  [M in keyof TelegramParameterSpec]: TelegramParamsFromSpec<TelegramParameterSpec[M]>;
};

type TelegramDocResultType<T extends string> =
  T extends 'Boolean' ? boolean :
  T extends 'String' ? string :
  T extends 'Integer' ? number :
  T extends `Array of ${infer Item}` ? Array<TelegramDocResultType<Item>> :
  T extends `${infer Left} | ${infer Right}` ? TelegramDocResultType<Left> | TelegramDocResultType<Right> :
  TelegramBotApiType<T>;

export type TelegramGeneratedMethodResults = {
  [M in keyof typeof TELEGRAM_METHOD_RESULT_SPEC]: TelegramDocResultType<(typeof TELEGRAM_METHOD_RESULT_SPEC)[M]>;
};

